{
 "title": "pizza dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "totalActiveUsers_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "active users"
    }
   ]
  },
  {
   "title": "Auth Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "rate(authSuccess_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(authFailure_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Requests Totals",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(requests_total{endpoint=\"[PUT] /api/auth\", source=\"jwt-pizza-service\"}[$__rate_interval])",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "rate(requests_total{endpoint=\"[DELETE] /api/auth\", source=\"jwt-pizza-service\"}[$__rate_interval])",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "rate(requests_total{endpoint=\"[GET] /api/order/menu\", source=\"jwt-pizza-service\"}[$__rate_interval])",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "rate(requests_total{endpoint=\"[POST] /api/order\", source=\"jwt-pizza-service\"}[$__rate_interval])",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "rate(totalRequests_total{source=\"jwt-pizza-service\"}[$__rate_interval])",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memoryUsage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpuUsage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "requestsLatency_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "Requests Latency"
    }
   ]
  },
  {
   "title": "Total Reveneu",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pizzaPurchasePrice_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "Total Reveneu"
    }
   ]
  },
  {
   "title": "Pizza Purchase per Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 28 },
   "targets": [
    {
     "expr": "rate(pizzaPurchaseSuccess_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "purchase success"
    },
    {
     "expr": "rate(pizzaPurchaseError_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "purchase failed"
    }
   ]
  },
  {
   "title": "Pizza Purchase Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "pizzaPurchaseLatency_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "latency"
    }
   ]
  }
 ]
}